### ISSUE TITLE
awsome,but what about bolts?

### ISSUE THREAD

**Issue by xuwenq** [filox/StormCpp#1]
spouts are supported , what about bolts?
‘“the executable split_sentence should reside in a directory that is on the system's path. This is due to a bug in Storm 0.7.4”
what is the bug？

**Comment by filox** [comment]
Bolts are both supported and tested.  Spouts are supported but not tested.

This is the bug in Storm: https://github.com/nathanmarz/storm/issues/229

Does this answer your question?  Can I close the issue?

**Comment by xuwenq** [comment]
thanks very much
